# Generated by Django 5.2.6 on 2025-11-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateTimeField(),
        ),
    ]
