# Generated by Django 5.2.6 on 2026-02-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientPortalApp', '0003_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address_city',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_country',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_line',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_postalcode',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
